Add loki persistence storage to s3 option
20tab/talos pull request #215
Opened 2023-01-10 16:58 UTC by trottomv

2023-01-10 17:50 UTC, pauloxnet requested changes
Separate generic upgrade changes from other specific with the goal of this PR

2023-01-11 08:25 UTC, trottomv commented
> Separate generic upgrade changes from other specific with the goal of this PR

We could leave only grafana to the current version which in any case, is updated to a minor version

2023-01-16 11:31 UTC, filippo-20tab requested changes

2023-01-16 11:31 UTC, filippo-20tab commented on {{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/monitoring/main.tf
> +      local.s3_host != "",
```suggestion
      var.s3_bucket_name != "",
      var.s3_host != "",
```

2023-01-16 11:31 UTC, filippo-20tab commented on {{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/monitoring/variables.tf
> +  description = "The S3 host url."
```suggestion
  description = "The S3 host."
```

2023-01-16 11:31 UTC, filippo-20tab commented on {{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/monitoring/main.tf
> +  values = local.s3_storage_enabled ? [file("${path.module}/loki/values.yaml")] : []
Let's discuss this. I find this solution is too limiting.

2023-01-16 11:31 UTC, filippo-20tab commented on {{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/routing/main.tf
> +}
These two resources do not have a real reason to exist. Let's change the other two, in order to have them depend on `local.basic_auth_ready`, and mount them according to `local.basic_auth_enabled` too (or not) as needed.

2023-01-16 13:17 UTC, trottomv commented on {{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/routing/main.tf
> +}
The other two "twins" resources are in a different namespace, unfortunately, so it becomes useful to keep them separate and keep this two as is.

2023-01-16 13:27 UTC, trottomv commented on {{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/monitoring/main.tf
> +  values = local.s3_storage_enabled ? [file("${path.module}/loki/values.yaml")] : []
A solution with concatenated values.yaml could be cleaner, I'll try to work on it

2023-01-17 08:16 UTC, filippo-20tab requested changes

2023-01-17 08:16 UTC, filippo-20tab commented on {{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/monitoring/main.tf
> +  )
```suggestion
  values = [
    file("${path.module}/loki/values.yaml"), 
    file(local.s3_storage_enabled ? "${path.module}/loki/s3_storage.yaml") : "${path.module}/loki/pvc_storage.yaml"))
  ]
```

2023-01-17 08:16 UTC, filippo-20tab commented on {{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/monitoring/loki/s3_storage.yaml
> +        # secret_access_key: <YOURDO_SPACES_SECRET_KEY_HERE>
Are these comments really necessary?

2023-01-17 08:16 UTC, filippo-20tab commented on {{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/routing/main.tf
>  resource "kubernetes_manifest" "traefik_basic_auth_middleware" {
I would remove the `-middleware` part from the `metadata.name` attribute of both Middlewares (leaving their Terraform resources name unaltered). There is no need to repeat their type inside their K8s name.

2023-01-17 09:11 UTC, trottomv commented on {{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/routing/main.tf
>  resource "kubernetes_manifest" "traefik_basic_auth_middleware" {
ok

2023-01-17 09:12 UTC, trottomv commented on {{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/monitoring/loki/s3_storage.yaml
> +        # secret_access_key: <YOURDO_SPACES_SECRET_KEY_HERE>
not really necessary, i can clean this part of yaml

2023-01-17 09:12 UTC, trottomv commented on {{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/monitoring/main.tf
> +  )
ok

2023-01-17 09:34 UTC, pauloxnet approved these changes

2023-01-17 09:37 UTC, merged