Add traefik healthcheck in docker-compose
20tab/talos pull request #220
Opened 2023-01-17 16:03 UTC by trottomv

2023-01-31 09:34 UTC, pauloxnet approved these changes

2023-02-08 17:32 UTC, filippo-20tab commented on {{cookiecutter.project_dirname}}/traefik/conf/static.yaml
> +
Is this a mistake?

2023-02-08 17:33 UTC, filippo-20tab commented on {{cookiecutter.project_dirname}}/docker-compose.yaml
> +      - "--configFile=/traefik/conf/static.yaml"
As you're refactoring it, I'd make it more compact
```suggestion
    command: "--configFile=/traefik/conf/static.yaml"
```

2023-02-08 17:35 UTC, filippo-20tab commented on {{cookiecutter.project_dirname}}/docker-compose.yaml
> +      retries: 5
Why these values specifically?

2023-02-12 10:18 UTC, daniele20tab commented
I don't understand the utility on have heathcheck on proxy services

2023-02-12 10:20 UTC, daniele20tab requested changes
I don't understand the utility on have heathcheck on proxy services.
And i don't see that implementation on the sprint plan.

2023-02-13 07:30 UTC, trottomv commented on {{cookiecutter.project_dirname}}/traefik/conf/static.yaml
> +
not a mistake, this would enable ping for healthcheck

2023-02-13 07:32 UTC, trottomv commented
> I don't understand the utility on have heathcheck on proxy services. And i don't see that implementation on the sprint plan.

we can consider it a spike to evaluate the effective need and close the PR without problems

2023-02-13 07:36 UTC, trottomv commented on {{cookiecutter.project_dirname}}/docker-compose.yaml
> +      retries: 5
these are experimental values

2023-02-13 18:13 UTC, filippo-20tab commented on {{cookiecutter.project_dirname}}/docker-compose.yaml
> +      retries: 5
Until a solid reason arise to use different values, I suggest adopting the default ones. The main Talos branch should not integrate experimental features.

2023-02-16 08:45 UTC, trottomv commented
to assess the real need in the future

2023-02-16 08:45 UTC, closed without merging