Feature/813 Add vulnerability assessment with trivy into Makefile
20tab/talos pull request #223
Opened 2023-01-18 22:24 UTC by trottomv

2023-01-19 09:54 UTC, pauloxnet requested changes

2023-01-19 09:54 UTC, pauloxnet commented on {{cookiecutter.project_dirname}}/Makefile
> +	--env CUSTOM_UID=`id -u` \
```suggestion
	--env CUSTOM_GID=`id --group` \
	--env CUSTOM_UID=`id --user` \
```

2023-01-19 09:54 UTC, pauloxnet commented on {{cookiecutter.project_dirname}}/scripts/trivy.sh
> +chown -R ${CUSTOM_UID}:${CUSTOM_GID} /app/.trivy
```suggestion
chown --recursive ${CUSTOM_UID}:${CUSTOM_GID} /app/.trivy
```

2023-01-19 14:16 UTC, trottomv commented on {{cookiecutter.project_dirname}}/Makefile
> +trivy:  ## Run image vulnerabilities scan with 'trivy'
```suggestion
trivy:  ## Run image vulnerabilities scan with ex. 'make trivy backend'
```

2023-01-19 14:16 UTC, trottomv commented on {{cookiecutter.project_dirname}}/Makefile
> +trivy:  ## Run image vulnerabilities scan with ex. 'make trivy backend'
```suggestion
trivy:  ## Run image vulnerabilities scan ex. 'make trivy backend'
```

2023-01-25 08:05 UTC, trottomv commented
consider it a spike for now, postponed

2023-01-25 08:05 UTC, closed without merging