TG-932 Refactor Traefik dynamic conf
20tab/talos pull request #231
Opened 2023-02-08 18:01 UTC by filippo-20tab

2023-02-09 09:00 UTC, trottomv approved these changes

2023-02-12 10:21 UTC, daniele20tab approved these changes

2023-02-12 11:07 UTC, daniele20tab requested changes

2023-02-12 11:07 UTC, daniele20tab commented on {{cookiecutter.project_dirname}}/traefik/conf/dynamic.yaml
> +        PathPrefix(`/sockjs-node`){% endif %}
Is no need specify sockjs-node that is only needed on nginx not on traefik
```suggestion
      rule: PathPrefix(`/`){% endif %}
```

2023-02-13 18:09 UTC, merged