TG-948 Fix gitignored tfvars
20tab/talos pull request #235
Opened 2023-02-20 18:00 UTC by filippo-20tab

2023-02-20 18:02 UTC, daniele20tab approved these changes

2023-02-21 07:59 UTC, pauloxnet requested changes

2023-02-21 07:59 UTC, pauloxnet commented on {{cookiecutter.project_dirname}}/.gitignore
> +terraform.tfvars.json
```suggestion
# Exclude all .tfvars files, which are likely to contain sensitive data, such as
# password, private keys, and other secrets. These should not be part of version
# control as they are data points which are potentially sensitive and subject
# to change depending on the environment.
# *.tfvars
# *.tfvars.json
```

I would suggest to comment the original code block and add your suggested lines at the bottom of the file, so that it's easier so compare and align `.gitignore` recipe from Github:

```
# Exclude terraform.tfvars files, as they are chosen to be used only locally.
terraform.tfvars
terraform.tfvars.json
```

2023-03-01 11:40 UTC, pauloxnet approved these changes

2023-03-01 11:41 UTC, merged