Change cache_url to redis_url
20tab/talos pull request #237
Opened 2023-03-01 12:23 UTC by filippo-20tab

The current secret holds the `CACHE_URL` value, as expected by the `django-cache-url` package. This prevents other potential components (e.g. Celery) to access the Redis server URL, which is contained in the `CACHE_URL` value but can not easily be used as-is. Therefore I suggest storing a `REDIS_URL` value with the Redis server URL, and then populate the `CACHE_URL` environment variable from it in the Django deployment, as proposed in the twin PR in the DJango-Talos subrepo.

2023-03-02 07:38 UTC, trottomv requested changes

2023-03-02 07:38 UTC, trottomv commented on {{cookiecutter.project_dirname}}/terraform/environment/other-k8s/main.tf
> +    REDIS_URL = module.redis[0].cache_url
I understand the need to have the flat CACHE_URL value without the prefix but I don't see the need to rename this environment variable, and would leave the naming at CACHE_URL.
I'll also leave a comment in the sister PR with a further proposal.

2023-03-02 09:33 UTC, filippo-20tab commented on {{cookiecutter.project_dirname}}/terraform/environment/other-k8s/main.tf
> +    REDIS_URL = module.redis[0].cache_url
There is no need to have a "flat" `CACHE_URL` value, the change was proposed in order to have a clean Redis server URL, meant to be used for whatever purpose a package other than Django might have. Therefore, the "cache" prefix would not be adequate. Besides, in order for the change to be small and backward compatible, `CACHE_URL` should stay as-is. The new variable would serve the other potential purposes without interfering or shadowing the original one.

2023-03-31 12:43 UTC, trottomv approved these changes

2023-03-31 12:43 UTC, pauloxnet approved these changes

2023-04-03 10:03 UTC, merged